**Laboratório 1:** <br>
Um exemplo de rede neural que aprende a tabela verdade do XOR utilizando regressão logística com a função de custo "binary cross-entropy" (Aula 3 - Slides 7 a 9).

In [1]:
import torch
from torch.nn.functional import binary_cross_entropy

torch.manual_seed(33); #Seed - Um número arbitrário

Abaixo está a implementação de uma função que inicializa os "weights" e "bias" das camadas. No exemplo, os "weights" são calculados utilizando a função descrita [neste artigo](http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf?hc_location=ufi]). Já o "bias" estão sendo inicializados com um valor arbitrário.

In [2]:
def init_weights(m):
    if type(m) == torch.nn.Linear:
        torch.nn.init.xavier_uniform_(m.weight)
        m.bias.data.fill_(0.01)

In [3]:
X = torch.tensor([[0, 0],
               [0, 1],
               [1, 0],
               [1, 1]], dtype=torch.float32)

print("X ", X)
print("")

y = torch.tensor([0, 1, 1, 0], dtype=torch.float32).reshape(X.shape[0], 1) #Reshape - Uma função que altera o 'shape', I.E. a disposições dos elementos de um tensor.
print("y ", y)
print("")

X  tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

y  tensor([[0.],
        [1.],
        [1.],
        [0.]])



In [4]:
model = torch.nn.Sequential(
    torch.nn.Linear(2, 2),
    torch.nn.Sigmoid(),
    torch.nn.Linear(2, 1),
    torch.nn.Sigmoid()
)

print("= Model =")
print(model)
print("")

model.apply(init_weights)

print("= Parameters =")
for param in model.parameters():
    print(param)
    print("")
print("")

optimizer = torch.optim.RMSprop(model.parameters(), lr = 0.03)

torch.set_printoptions(precision=3, sci_mode=False)

= Model =
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=2, out_features=1, bias=True)
  (3): Sigmoid()
)

= Parameters =
Parameter containing:
tensor([[-0.6456, -0.3179],
        [ 1.0210, -1.1431]], requires_grad=True)

Parameter containing:
tensor([0.0100, 0.0100], requires_grad=True)

Parameter containing:
tensor([[ 0.6173, -1.3222]], requires_grad=True)

Parameter containing:
tensor([0.0100], requires_grad=True)




In [5]:
EPOCHS = 100

for epoch in range(EPOCHS):
  #forward
  y_est = model(X)
  
  #compute mean squared error loss
  loss = binary_cross_entropy(y_est, y)

  #backprop the loss gradients
  loss.backward()

  #update the model weights using the gradients
  optimizer.step()

  #empty the gradients for the next iteration
  optimizer.zero_grad()

print("Weights")
for param in model.parameters():
  print(param.data)
print("")

print("Input -> Output")
for x in X:
  print(x, " -> ", model(x))

Weights
tensor([[ 4.902, -5.006],
        [ 5.734, -5.341]])
tensor([-2.698,  2.847])
tensor([[ 5.407, -5.253]])
tensor([2.469])

Input -> Output
tensor([0., 0.])  ->  tensor([0.104], grad_fn=<SigmoidBackward>)
tensor([0., 1.])  ->  tensor([0.888], grad_fn=<SigmoidBackward>)
tensor([1., 0.])  ->  tensor([0.890], grad_fn=<SigmoidBackward>)
tensor([1., 1.])  ->  tensor([0.093], grad_fn=<SigmoidBackward>)
